<?php


$S1 = "w3-blue";        // Leading cell
$S2 = "w3-indigo";      // First pass, round, arrow, target, or section
$S3 = "w3-deep-purple"; // Second pass, round, arrow, target, or section
$S4 = "w3-purple";      // Third pass, round, arrow, target, or section
$S5 = "w3-pink";        // Submission/Reset buttons -- Diagnostic parent
$S6 = "w3-indigo";      // Review leading cell
$S7 = "w3-indigo";      // Review Submission/Edit buttons -- Diagnostic parent
$BG = "steelblue";      // Color under cells
$L1 = "w3-ikeqc1";      // IKEqC Logo BG Color
$L2 = "w3-ikeqc2";      // IKEqC dilute BG Color (first step)
$L3 = "w3-ikeqc3";      // IKEqC dilute BG Color (second step)