<?php
// Development Data
$EName = "Sample Wars III";
$RiderHonors = "Earl Sir";
$RiderName = "Earl";
$RiderID = 999;
$RiderDVN = 1;
$run = 999;
$RunHeads = true;
$RunRings = true;
$RunReeds = true;
$RunMoarch = true;
$RunBirjas = true;

$_SESSION['RiderHonors'] = $RiderHonors;
$_SESSION['RiderName'] = $RiderName;
$_SESSION['RiderID'] = $RiderID;
$_SESSION['RiderDVN'] = $RiderDVN;
$_SESSION['EName'] = $EName;
$_SESSION['BG'] = $BG;
