<?php
// Development Data
$EName = "Sample Wars III";
$RiderHonors = "Earl Sir";
$RiderName = "Earl";
$RiderID = 999;
$RiderDVN = 1;
$run = 999;


$_SESSION['RunH21'] = true;
$_SESSION['RunH30'] = true;
$_SESSION['RunRings'] = true;
$_SESSION['RunReeds'] = true;
$_SESSION['RunMA1'] = true;
$_SESSION['RunMA3'] = true;
$_SESSION['RunBirjas'] = true;
$_SESSION['RiderHonors'] = $RiderHonors;
$_SESSION['RiderName'] = $RiderName;
$_SESSION['RiderID'] = $RiderID;
$_SESSION['RiderDVN'] = $RiderDVN;
$_SESSION['EName'] = $EName;
$_SESSION['BG'] = $BG;
