<?PHP
// MA1.inc
// Include file with the settings of scoring for 'Petite Mounted Archery' aka Single Shot
// File v0.2a
// Last Updated: 5 FEB 2017
// Sandor Dosa

// NOTE: This is a six-fold increase above Grand Mounted Archery.

$Gold = 30;                      //Bullseye of Target
$Red = 24;                       //First Ring
$Blue = 18;                      //Second Ring
$Black = 12;                     //Third Ring
$White = 6;                      //Outer Ring
$Bounce = 0;                     //Shots that strike but do not stick in the target
$Passthru = 0;                   //Shots that pass thru the target
$Dropout = 0;                    //Shots that strike, stick for a moment and then drop out
$Technical = 10;                  //Score added for proper control and technical form (i.e. consolation point(s)

?>



